/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTB1 (number 17), J8[2]/ADC0_SE5/CMP0_IN3/UART0_TX/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_TX_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB2 (number 18), J8[1]/ADC0_SE4/UART0_RX/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_RX_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA8 (number 19), J10[6]/ADC0_SE3/I2C1_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_echo1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_echo1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_echo1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_echo1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_echo1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_echo1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTA9 (number 20), J10[5]/ADC0_SE2/I2C1_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_trigger1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_trigger1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_trigger1_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_trigger1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_trigger1_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_trigger1_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB13 (number 29), J10[3]/ADC0_SE13
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_echo2_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_echo2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_echo2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_echo2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_echo2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_echo2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTB9 (number 12), J10[2]/ADC0_SE10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_trigger2_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_trigger2_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_trigger2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_trigger2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_trigger2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_trigger2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
